### ISSUE TITLE
Pi does not know when a car is staged

### ISSUE THREAD

**Issue by bristolmotorclub** [bristolmotorclub/autosolo-timing#1]
Pi needs to query timing service to return when a car is staged.  Indicator for driver when car is staged and ready to go - LED or OLED with text.

Michael is adding an endpoint.  Will return 2xx when a car is staged and 4xx otherwise.

**Comment by mabware** [comment]
slight change of plan, I've added getters to each stage as well at the existing /currentState endpoint that gives all states

suggest the Pi call GET /stage and checks for an array of length 1 in the response body see [commit](https://github.com/mabware/timing-reconciliation-api/commit/a01dd9e5802a2993aa96873abf3fcee8ca0da0da)

Also if you use a socket-io python client you can do a re-fetch on 'stateUpdate' which is emitted everytime a driver changes state see [commit](https://github.com/mabware/timing-reconciliation-api/commit/65d7ba1407b24f937025a30967ef5e0b63670b3a)
