### ISSUE TITLE
Penalty options for finished cars

### ISSUE THREAD

**Issue by bristolmotorclub** [bristolmotorclub/autosolo-timing#3]
Add buttons for finished cars.  One option must be selected bfore the time is lodged:

- Clean run
- Penalty (1-6 cones)
- Wrong Test
- Cancel run
- Accidental finish trigger (move finish event to next trigger of finish)

Screen should also show the finishing time for validation.

**Comment by mabware** [comment]
@bristolmotorclub UI will probably need some tweaking, but functionality should be there
